# Generated by Django 4.2.7 on 2023-11-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customer_address_alter_customer_photo_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='photo_number',
            new_name='phone_number',
        ),
    ]
