# Generated by Django 4.2.7 on 2023-11-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_photo_number_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='joined_date',
        ),
    ]
